# Generated by Django 3.1.1 on 2020-11-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201123_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Address'),
        ),
    ]
