# Generated by Django 3.1.1 on 2020-11-24 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201124_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=500, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(default=datetime.date.today, help_text='YYYY-MM-DD', verbose_name='Day'),
        ),
    ]
