# Generated by Django 3.1.1 on 2020-11-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201124_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
